package com.example.data

import android.content.Context
import android.util.Log
import com.example.BuildConfig
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions
import com.google.firebase.firestore.DocumentChange
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.CoroutineExceptionHandler

object FirebaseSyncManager {
    private const val TAG = "FirebaseSync"
    private var isInitialized = false
    private var vehicleListener: ListenerRegistration? = null
    private var bookingListener: ListenerRegistration? = null
    
    private val exceptionHandler = CoroutineExceptionHandler { _, exception ->
         Log.e(TAG, "Coroutine Sync Uncaught Exception: ", exception)
    }
    private val coroutineScope = CoroutineScope(Dispatchers.IO + SupervisorJob() + exceptionHandler)

    fun isConfigured(): Boolean {
        // Safe check for BuildConfig parameters generated by Secrets Gradle Plugin
        val apiKey = try { BuildConfig.FIREBASE_API_KEY.trim('"', ' ') } catch (e: Throwable) { "" }
        val appId = try { BuildConfig.FIREBASE_APPLICATION_ID.trim('"', ' ') } catch (e: Throwable) { "" }
        val pId = try { BuildConfig.FIREBASE_PROJECT_ID.trim('"', ' ') } catch (e: Throwable) { "" }
        
        if (apiKey.isEmpty() || apiKey.contains("YOUR_") || apiKey == "MY_API_KEY" || apiKey == "null" || apiKey == "undefined") return false
        if (appId.isEmpty() || appId.contains("YOUR_") || appId == "null" || appId == "undefined") return false
        if (pId.isEmpty() || pId.contains("YOUR_") || pId == "null" || pId == "undefined") return false
        
        // Firebase project IDs must start with a lowercase letter, contain only lowercase letters, numbers, or hyphens, and be 4-30 chars
        val projectIdRegex = Regex("^[a-z0-9-]+$")
        if (!projectIdRegex.matches(pId)) {
            Log.e("FirebaseSync", "Firebase Project ID '$pId' is invalid (must contain only lowercase letters, numbers, and hyphens) - running in Offline Mode")
            return false
        }
        return true
    }

    fun initialize(context: Context): Boolean {
        if (isInitialized) return true
        if (!isConfigured()) return false
        return try {
            val apps = FirebaseApp.getApps(context)
            if (apps.any { it.name == FirebaseApp.DEFAULT_APP_NAME }) {
                isInitialized = true
                Log.d(TAG, "Firebase default instance already exists.")
                return true
            }

            val apiKey = BuildConfig.FIREBASE_API_KEY.trim('"', ' ')
            val appId = BuildConfig.FIREBASE_APPLICATION_ID.trim('"', ' ')
            val pId = BuildConfig.FIREBASE_PROJECT_ID.trim('"', ' ')

            val options = FirebaseOptions.Builder()
                .setApiKey(apiKey)
                .setApplicationId(appId)
                .setProjectId(pId)
                .build()
            
            FirebaseApp.initializeApp(context.applicationContext, options)
            isInitialized = true
            Log.d(TAG, "Firebase initialized programmatically successfully!")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Firebase programmatic initialization failed", e)
            false
        }
    }

    fun startBilateralSync(context: Context, database: AppDatabase) {
        if (!initialize(context)) {
            Log.d(TAG, "BilateralSync: Firebase not configured or initialization failed.")
            return
        }

        try {
            val db = FirebaseFirestore.getInstance()
            Log.d(TAG, "BilateralSync: Starting real-time Firestore synchronization listeners...")

            // 1. Synchronize "vehicles" collection
            vehicleListener?.remove()
            vehicleListener = db.collection("vehicles")
                .addSnapshotListener { snapshots, error ->
                    if (error != null) {
                        Log.e(TAG, "Vehicles subscription error", error)
                        return@addSnapshotListener
                    }
                    if (snapshots != null) {
                        coroutineScope.launch {
                            for (doc in snapshots.documentChanges) {
                                try {
                                    val vehicleMap = doc.document.data
                                    val vehicleId = doc.document.id.toLongOrNull() ?: continue
                                    val vehicle = parseVehicle(vehicleMap, vehicleId) ?: continue
                                    
                                    when (doc.type) {
                                        DocumentChange.Type.ADDED,
                                        DocumentChange.Type.MODIFIED -> {
                                            database.vehicleDao().insertVehicle(vehicle)
                                            Log.d(TAG, "Firestore sync: inserted/updated vehicle ${vehicle.id}")
                                        }
                                        DocumentChange.Type.REMOVED -> {
                                            database.vehicleDao().deleteVehicle(vehicle)
                                            Log.d(TAG, "Firestore sync: deleted vehicle ${vehicle.id}")
                                        }
                                    }
                                } catch (ex: Exception) {
                                    Log.e(TAG, "Error handling vehicle sync item", ex)
                                }
                            }
                        }
                    }
                }

            // 2. Synchronize "bookings" collection
            bookingListener?.remove()
            bookingListener = db.collection("bookings")
                .addSnapshotListener { snapshots, error ->
                    if (error != null) {
                        Log.e(TAG, "Bookings subscription error", error)
                        return@addSnapshotListener
                    }
                    if (snapshots != null) {
                        coroutineScope.launch {
                            for (doc in snapshots.documentChanges) {
                                try {
                                    val bookingMap = doc.document.data
                                    val bookingId = doc.document.id.toLongOrNull() ?: continue
                                    val booking = parseBooking(bookingMap, bookingId) ?: continue

                                    when (doc.type) {
                                        DocumentChange.Type.ADDED,
                                        DocumentChange.Type.MODIFIED -> {
                                            database.bookingDao().insertBooking(booking)
                                            Log.d(TAG, "Firestore sync: inserted/updated booking ${booking.id}")
                                        }
                                        DocumentChange.Type.REMOVED -> {
                                            // Handle deletion if required
                                        }
                                    }
                                } catch (ex: Exception) {
                                    Log.e(TAG, "Error handling booking sync item", ex)
                                }
                            }
                        }
                    }
                }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to register real-time synchronization listeners", e)
        }
    }

    fun stopSync() {
        vehicleListener?.remove()
        vehicleListener = null
        bookingListener?.remove()
        bookingListener = null
    }

    // Bidirectional Cloud writers
    fun pushVehicleToCloud(vehicle: VehicleEntity) {
        if (!isInitialized) return
        coroutineScope.launch {
            try {
                val db = FirebaseFirestore.getInstance()
                db.collection("vehicles")
                    .document(vehicle.id.toString())
                    .set(vehicleToMap(vehicle), SetOptions.merge())
                    .addOnSuccessListener { Log.d(TAG, "Cloud update: Saved vehicle ${vehicle.id}") }
                    .addOnFailureListener { Log.e(TAG, "Cloud update: Failed to save vehicle ${vehicle.id}", it) }
            } catch (e: Exception) {
                Log.e(TAG, "Error pushing vehicle ${vehicle.id}", e)
            }
        }
    }

    fun deleteVehicleFromCloud(vehicle: VehicleEntity) {
        if (!isInitialized) return
        coroutineScope.launch {
            try {
                val db = FirebaseFirestore.getInstance()
                db.collection("vehicles")
                    .document(vehicle.id.toString())
                    .delete()
                    .addOnSuccessListener { Log.d(TAG, "Cloud update: Deleted vehicle ${vehicle.id}") }
            } catch (e: Exception) {
                Log.e(TAG, "Error deleting vehicle ${vehicle.id}", e)
            }
        }
    }

    fun pushBookingToCloud(booking: BookingEntity) {
        if (!isInitialized) return
        coroutineScope.launch {
            try {
                val db = FirebaseFirestore.getInstance()
                db.collection("bookings")
                    .document(booking.id.toString())
                    .set(bookingToMap(booking), SetOptions.merge())
                    .addOnSuccessListener { Log.d(TAG, "Cloud update: Saved booking ${booking.id}") }
                    .addOnFailureListener { Log.e(TAG, "Cloud update: Failed to save booking ${booking.id}", it) }
            } catch (e: Exception) {
                Log.e(TAG, "Error pushing booking ${booking.id}", e)
            }
        }
    }

    // Safe parser helpers
    private fun parseVehicle(map: Map<String, Any>, docId: Long): VehicleEntity? {
        return try {
            VehicleEntity(
                id = docId,
                ownerName = map["ownerName"] as? String ?: "",
                ownerBlock = map["ownerBlock"] as? String ?: "",
                ownerFlat = map["ownerFlat"] as? String ?: "",
                ownerPhone = map["ownerPhone"] as? String ?: "",
                model = map["model"] as? String ?: "",
                type = map["type"] as? String ?: "",
                regNumber = map["regNumber"] as? String ?: "",
                rentPerHour = (map["rentPerHour"] as? Number)?.toDouble() ?: 0.0,
                availabilityHours = map["availabilityHours"] as? String ?: "",
                desc = map["desc"] as? String ?: "",
                status = map["status"] as? String ?: "Available",
                isEv = map["isEv"] as? Boolean ?: false,
                imageUri = map["imageUri"] as? String,
                timestamp = (map["timestamp"] as? Number)?.toLong() ?: System.currentTimeMillis()
            )
        } catch (e: Exception) {
            null
        }
    }

    private fun parseBooking(map: Map<String, Any>, docId: Long): BookingEntity? {
        return try {
            BookingEntity(
                id = docId,
                vehicleId = (map["vehicleId"] as? Number)?.toLong() ?: 0L,
                vehicleModel = map["vehicleModel"] as? String ?: "",
                vehicleType = map["vehicleType"] as? String ?: "",
                ownerName = map["ownerName"] as? String ?: "",
                ownerBlock = map["ownerBlock"] as? String ?: "",
                ownerFlat = map["ownerFlat"] as? String ?: "",
                ownerPhone = map["ownerPhone"] as? String ?: "",
                renterName = map["renterName"] as? String ?: "",
                renterBlock = map["renterBlock"] as? String ?: "",
                renterFlat = map["renterFlat"] as? String ?: "",
                renterPhone = map["renterPhone"] as? String ?: "",
                rentPerHour = (map["rentPerHour"] as? Number)?.toDouble() ?: 0.0,
                hours = (map["hours"] as? Number)?.toInt() ?: 1,
                totalPrice = (map["totalPrice"] as? Number)?.toDouble() ?: 0.0,
                notes = map["notes"] as? String ?: "",
                bookingDate = map["bookingDate"] as? String ?: "Today",
                startHour = (map["startHour"] as? Number)?.toInt() ?: 9,
                status = map["status"] as? String ?: "Requested",
                timestamp = (map["timestamp"] as? Number)?.toLong() ?: System.currentTimeMillis()
            )
        } catch (e: Exception) {
            null
        }
    }

    private fun vehicleToMap(v: VehicleEntity): Map<String, Any> {
        return mapOf(
            "ownerName" to v.ownerName,
            "ownerBlock" to v.ownerBlock,
            "ownerFlat" to v.ownerFlat,
            "ownerPhone" to v.ownerPhone,
            "model" to v.model,
            "type" to v.type,
            "regNumber" to v.regNumber,
            "rentPerHour" to v.rentPerHour,
            "availabilityHours" to v.availabilityHours,
            "desc" to v.desc,
            "status" to v.status,
            "isEv" to v.isEv,
            "imageUri" to (v.imageUri ?: ""),
            "timestamp" to v.timestamp
        )
    }

    private fun bookingToMap(b: BookingEntity): Map<String, Any> {
        return mapOf(
            "vehicleId" to b.vehicleId,
            "vehicleModel" to b.vehicleModel,
            "vehicleType" to b.vehicleType,
            "ownerName" to b.ownerName,
            "ownerBlock" to b.ownerBlock,
            "ownerFlat" to b.ownerFlat,
            "ownerPhone" to b.ownerPhone,
            "renterName" to b.renterName,
            "renterBlock" to b.renterBlock,
            "renterFlat" to b.renterFlat,
            "renterPhone" to b.renterPhone,
            "rentPerHour" to b.rentPerHour,
            "hours" to b.hours,
            "totalPrice" to b.totalPrice,
            "notes" to b.notes,
            "bookingDate" to b.bookingDate,
            "startHour" to b.startHour,
            "status" to b.status,
            "timestamp" to b.timestamp
        )
    }
}
